services:
  app:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/
      AVATAR_API_URL: http://avatar_api:8080
    networks:
      - avatar_api
      - database
    depends_on:
      - mongo
      - avatar_api

  avatar_api:
    build:
      context: avatar_api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - avatar_api

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db
    networks:
      - database

volumes:
  db-data:

networks:
  avatar_api:
  database:
