services:
  app:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/

  avatar_api:
    build:
      context: avatar_api
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db

volumes:
  db-data:
